version: '3'

services:
  db:
    image: postgres:10-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./:/project
    # command: sh -c 'python manage.py wait_for_db && python manage.py migrate &&  python manage.py runserver 0.0.0.0:8000'
    command: sh -c 'sleep 365d'
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
    depends_on:
      - db
